---
name: Build CI
on: [push]  # yamllint disable-line rule:truthy
jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - {
            name: "Windows MSVC",
            enabled: 1,
            os: windows-latest,
            deps: "vcpkg install liblo --triplet x64-windows",
            config: "cmake -DCMAKE_TOOLCHAIN_FILE=C:/vcpkg/scripts/buildsystems/vcpkg.cmake .",
            debugprint: "Get-Content C:/vcpkg/packages/liblo_x64-windows/lib/pkgconfig/liblo.pc",
            build: "cmake --build .",
          }
          - {
            name: "Ubuntu gcc",
            enabled: 1,
            os: ubuntu-latest,
            deps: "sudo apt-get install liblo-dev",
            config: "mkdir build && cd build && cmake ..",
            debugprint: "echo",
            build: "cd build && make",
          }
    steps:
      - uses: actions/checkout@v3
      - name: install_deps
        if: ${{ matrix.config.enabled == 1 }}
        run: ${{ matrix.config.deps }}
      - name: configure
        if: ${{ matrix.config.enabled == 1 }}
        run: ${{ matrix.config.config }}
      - name: debugprint
        if: ${{ matrix.config.enabled == 1 }}
        run: ${{ matrix.config.debugprint }}
      - name: make
        if: ${{ matrix.config.enabled == 1 }}
        run: ${{ matrix.config.build }}
